language: node_js
services:
- docker
node_js:
- '8'
before_install:
- npm install -g @angular/cli
install:
- npm install
- webdriver-manager update
- pip install transifex-client
before_script:
- sh -e /etc/init.d/xvfb start
script:
- tx push --source
- tx pull --mode sourceastranslation -l he,en
- ng lint
- ng test --no-watch
- ng build --prod --configuration=production
- docker build . -t $DOCKER_REPO:latest
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
env:
  global:
  - DBUS_SESSION_BUS_ADDRESS=/dev/null
  - DISPLAY=:99.0
  - CHROME_BIN=chromium-browser
  - DOCKER_REPO: akariv/dgp-ui
  - secure: bN3yG8OA11HNLbTXjHPMEL13v+o9J8oN6jxdSALREjgTyZi3BH0erhR7IL0HTzs1UZzNPWt/6XjmOF7/LYRpiZwoDX5UnyhieZdzcrQu5pEEqNOxjqQUDYR0u7cdQ/y/nuNt6eajeOCMRYX6XbBy6FXWFS4i49gM4BrtTE6eLPDOwnv3hKPeUaxjK7hHjaqhuCSXK0q79co/ZyWB0N6pzcX42oJW1rW+dpb9D75J/2PkeG5nj84MakFHFvS+/2lUt3EO3pZ8VqeEesbNRYpMeAy6+Xi08uMl0PvqXew6cfR3tijJOnCHh2Ju2JRMY8Izcn9fs3F6lU+V5MtDV4SgsFYQcy9+Xtgd+ufmjqfhyXs1mSWP8P3pONqA5Mm2yMz3SKV4t4cefmHSrAZ4n+jxKe26cq06XJuG9H8qG9rqFc+pTf/RGkekbDadtJLSDz2fWeQwxbhGUVKpcksT96mBdKFVkeSeHw1bkv7DS9mZTJGUb47eFlxOgXJ55Er1SrUikNEYYI6q3XHpC8y90nad8txkOp31MQfR02PiPpsgcfLLpDq7lJdsiWJ8UHPk/asjdshmae5c4QHpdkf7kApSdM2IxpNcihbZwoX0KjizhUQXIxjQZ1qsCDE9ejHt+mlN3mknafh5hBBfEADKQ5m+d7pE4GDZPJjX59h8N+HM3Uk=
  - secure: VfUeVVba9eVGATTyn3s5HHxNM740IEPMiEo72+6kQGC2+vgc57Ok56wGHyxzMAigLA+uC7WlCN4bwysslffJszPKYajpPNRrBHh/EKDKK9CbJolawab6zwKBQiWzVtuhcNV6L3J9PvlfTtwctMjgZlQmahb+e29LBKsVQecGlZl4Hen0c5nvfHY9ZzmApi4Po7aZFjE0bPoYKnXA+xOW3goUNnfZtuXpJQzolaDLzw+7F3udEdTcClb186JF7ANkjlJ53W750OtXWE29l+EIyCWnHAWYAkgJefXyj7JH1BjmP+jrfvOXjxuYetIl0YXXTWmbQNgJDschr4wXuJZxHtfNIMLt8+qpKywzmVgyuCN73+46S0/LsJc/ICAcuaCcTn6SJYxjytR9IaExk+riDjINdp1w6nXnDoGaJGlhVJMyVChl7yoLpHUaNYTxVXwWNzzPqE7J+ZLfT7G3lywZywITtX8ogYtGoQBDnsSGT2A+uSLUhn+XE8PBSUEC5YCrWeGcm4tcO5vXebfdZdas+Tzen42+GEiWonSTfxJd55diDIGqkb8gRyUVw7+7vosNTNcnCJO0SMl/HZKYvdwhIjq4TLoesJreR19ub5KbPW/3qpEpxsJH/G0/5Il0lfF7Ac7bYTBcQ0UwfojeT3v2JAzBXN631GsRhubaSHUN7O0=
  - secure: JiiBG99HqlNeZ1kKUOV1wBlUQaeCOTwfjPcG0vDEptKiuXfrY6ik6sgwJD23ZLvyTYrgDE2ZyGTPSoI3KOjMEfo39rq0B06CkrXiF+OlG9SKX+Z4psAxBw98mZn5ibq0f9Fw3OK7i487rAEFmqPIkHVFFI1T2HhAXsrAaumaSGsSmdcCVLgdLDeetuu9CbuMLSxb7pF+5suUoTNo/3Xi82tmQsGGHkDasCkPIlhstIlUuBH1MtU+/B+nFIJF//Ld48GIvkyciIP3qUfqmSi8EHLDeqCLXRqsysRihGn7qN0S6Ns0KsYgVgAF2lnf7OLuhApydsNdNDrZ1rRqymnvTjaJTrTCsO3aPvE/HJ1XRDrmmGkok2MXETg0kVhOXWJoO4trwOHBH7Kb3hRen5tua0C/hLBSFinJGW4TYgILUnokaH70F17/uWrZ/NjM8MyxX+U5EkIQ3NSixCuw3A49sz+a5kVMuRBxtR6LoKUWBWsR8llBIc5WqPhb55P13CHR46ozWSq8Dc4O2GvmlL2it4nNO/MV2Lr4EKlvE/CyhvwulHQl17YbFuf2y3Jjm2dS/wFpD3ysm0e/bF8u4WcGQOmht9L1IPvf1fu7hfa0BgwblS/kK5kvbQDCYkEv+/SM/ikTD5vI7EUyDrO5/+4lrdssPf/yKLp13x5TkFkfmLQ=
